Update README.ja.md
YunzheZJU/holo-schedule pull request #40
Opened 2020-12-16 12:05 UTC by TeepaBlue

Add Japanese Readme

2020-12-16 12:17 UTC, YunzheZJU commented
Thank you for your contribution! I'm not good at Japanese so this README.ja is still left untouched. You did it and this really surprises me. I will check the paragraph formats later and merge this PR in 24 hours. 
If you find any suggestion when reading the original README, feel free to add your own words or delete some lines. Your contribution is going to help the other JP developers!

2020-12-16 12:25 UTC, YunzheZJU commented
@taizan-hokuto @ReiRokusanami0010 @hidori-11 Would you like to review this pull-request? You are mentioned since you have contributed to this project recently. Please ignore this message if you are busy. Sorry for my bothering.

2020-12-16 12:45 UTC, ReiRokusanami0010 commented
I think this translation is fine. 👍

2020-12-16 12:50 UTC, YunzheZJU commented
> I think this translation is fine. 👍

Thank you for your time!

2020-12-16 16:29 UTC, YunzheZJU requested changes
Nice job! I found some issues and want to request some changes before your contribution is merged finally. Would you please have a check?

2020-12-16 16:29 UTC, YunzheZJU commented on docs/README.ja.md
> +[Eng](/README.md) [中文](docs/README.zh_CN.md)
Let's prefer the absolute path. This fixes the broken link to `README.zh_CN.md`.
```suggestion
[Eng](/README.md) [中文](/docs/README.zh_CN.md)
```

2020-12-16 16:29 UTC, YunzheZJU commented on docs/README.ja.md
> +または
A doubled space will lead to an unexpected new line. Ignore this suggestion if this new line is intended.
```suggestion
または
```

2020-12-16 16:29 UTC, YunzheZJU commented on docs/README.ja.md
> +[![Chrome Web Store](./available-in-the-chrome-web-store.png)](https://chrome.google.com/webstore/detail/holoschedule/fjicegllhddldnnkgfefblholeegpcad)
I have created a [PR](https://github.com/YunzheZJU/holo-schedule/pull/41/files) to change all relative paths in README.md to absolute ones. 
```suggestion
[![Mozilla AMO](/docs/get-the-add-on.png)](https://addons.mozilla.org/firefox/addon/holo-schedule/)
[![Chrome Web Store](/docs/available-in-the-chrome-web-store.png)](https://chrome.google.com/webstore/detail/holoschedule/fjicegllhddldnnkgfefblholeegpcad)
```

2020-12-16 16:29 UTC, YunzheZJU commented on docs/README.ja.md
> +ソースコードからビルドして、手動でブラウザに入れる方法
Let's keep the terminator as line#86 uses it.
```suggestion
ソースコードからビルドして、手動でブラウザに入れる方法。
```

2020-12-16 23:37 UTC, TeepaBlue commented
It's all good!

2020-12-18 01:27 UTC, TeepaBlue commented
I fixed that.

2020-12-18 04:41 UTC, YunzheZJU approved these changes

2020-12-18 04:42 UTC, merged

2020-12-18 04:42 UTC, YunzheZJU commented
Thank you again for your contribution!